# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy to Production

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js 12.9.0
      uses: actions/setup-node@v1
      with:
        node-version: '12.9.0'
    - name: Clean install modules
      run: npm ci
    - name: Run build
      run: npm run build --if-present
      env:
        NODE_ENV: production
    - name: Deploy studio to server
      uses: easingthemes/ssh-deploy@v2.1.1
      if: ${{ github.repository == 'luigimannoni/sanity-nextks-landing-pages' }}
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "studio/dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_STUDIO_TARGET }}
    - name: Deploy web folder
      uses: easingthemes/ssh-deploy@v2.1.1
      if: ${{ github.repository == 'luigimannoni/sanity-nextks-landing-pages' }}
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "web/out/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_WEB_TARGET }}
